// Generated by scripts/generate_contracts.py. Do not edit.
export interface Country {
  id: string;
  name: string;
  aggregate: boolean;
}
export interface Observation {
  date: string;
  value: number | null;
  realtime_start: string;
  realtime_end: string;
}
export interface ProviderStatus {
  fred_configured: boolean;
}
export interface SearchResult {
  items: Array<Series>;
  total: number;
  page: number;
  page_size: number;
}
export interface Series {
  provider: 'fred' | 'worldbank';
  id: string;
  title: string;
  source_id: string;
  source_name: string;
  units: string;
  frequency: string;
  seasonal_adjustment: string;
  notes: string;
  source_url: string;
  license_url: string;
  updated: string;
}
export interface Snapshot {
  series: Series;
  country: string;
  retrieved_at: string;
  snapshot_id: string;
  raw_sha256: Array<string>;
  vintage: string;
  transformations: Array<string>;
  requested_start: string;
  requested_end: string;
  observations: Array<Observation>;
}
