// Generated by scripts/generate_contracts.py. Do not edit.
export interface Accuracy {
  count: number;
  mae: number;
  rmse: number;
  mase: number | null;
  coverage: number;
}
export interface AnalysisRequest {
  snapshot_id: string;
  start: string;
  end: string;
  frequency: 'auto' | 'annual' | 'quarterly' | 'monthly' | 'weekly' | 'daily';
  transform: 'level' | 'difference' | 'pct_change' | 'log' | 'rolling_mean';
  lag: number;
  window: number;
}
export interface AnalysisResult {
  snapshot_id: string;
  frequency: string;
  transform: 'level' | 'difference' | 'pct_change' | 'log' | 'rolling_mean';
  units: string;
  observations: Array<Observation>;
  statistics: Statistics;
  autocorrelation: Array<Correlation>;
  warnings: Array<string>;
}
export interface Correlation {
  lag: number;
  value: number;
}
export interface Country {
  id: string;
  name: string;
  aggregate: boolean;
}
export interface CsvImportRequest {
  content: string;
  title: string;
  date_column: string;
  value_column: string;
  units: string;
  frequency: 'annual' | 'quarterly' | 'monthly' | 'weekly' | 'daily';
}
export interface CsvPreview {
  columns: Array<string>;
  rows: Array<Array<string>>;
  count: number;
}
export interface EvaluationPoint {
  date: string;
  value: number;
  lower: number;
  upper: number;
  origin: string;
  horizon: number;
  actual: number;
  scale: number | null;
}
export interface ForecastPoint {
  date: string;
  value: number;
  lower: number;
  upper: number;
}
export interface ForecastRequest {
  snapshot_id: string;
  start: string;
  end: string;
  frequency: 'auto' | 'annual' | 'quarterly' | 'monthly' | 'weekly' | 'daily';
  missing: 'reject' | 'trim_edges';
  horizon: number;
  folds: number;
  interval: 80 | 95;
  models: Array<'naive' | 'drift' | 'seasonal_naive' | 'ets' | 'sarima'>;
  options: ModelOptions;
}
export interface ForecastRun {
  run_id: string;
  created_at: string;
  engine_version: string;
  title: string;
  units: string;
  country: string;
  request: ForecastRequest;
  frequency: string;
  history: Array<Observation>;
  models: Array<ModelResult>;
  warnings: Array<string>;
  assumptions: Array<string>;
  environment: Array<NamedValue>;
}
export interface HorizonAccuracy {
  count: number;
  mae: number;
  rmse: number;
  mase: number | null;
  coverage: number;
  horizon: number;
}
export interface ModelOptions {
  p: number;
  d: number;
  q: number;
  seasonal_p: number;
  seasonal_d: number;
  seasonal_q: number;
  seasonal_period: number;
  sarima_trend: 'none' | 'constant';
  ets_trend: boolean;
  ets_damped: boolean;
  ets_seasonal: boolean;
}
export interface ModelResult {
  model: 'naive' | 'drift' | 'seasonal_naive' | 'ets' | 'sarima';
  status: 'success' | 'failed';
  error: string;
  forecast: Array<ForecastPoint>;
  validation: Accuracy | null;
  holdout: Accuracy | null;
  by_horizon: Array<HorizonAccuracy>;
  validation_points: Array<EvaluationPoint>;
  holdout_points: Array<EvaluationPoint>;
  residuals: Array<Observation>;
  diagnostics: ResidualDiagnostics | null;
  parameters: Array<NamedValue>;
  warnings: Array<string>;
}
export interface NamedValue {
  name: string;
  value: string;
}
export interface Observation {
  date: string;
  value: number | null;
  realtime_start: string;
  realtime_end: string;
}
export interface ProviderStatus {
  fred_configured: boolean;
}
export interface ResidualDiagnostics {
  count: number;
  mean: number;
  ljung_box_lag: number;
  ljung_box_pvalue: number | null;
  degrees_of_freedom: number;
}
export interface RunSummary {
  run_id: string;
  created_at: string;
  title: string;
  country: string;
  horizon: number;
  frequency: string;
  models: Array<string>;
}
export interface SearchResult {
  items: Array<Series>;
  total: number;
  page: number;
  page_size: number;
}
export interface Series {
  provider: 'fred' | 'worldbank' | 'local';
  id: string;
  title: string;
  source_id: string;
  source_name: string;
  units: string;
  frequency: string;
  seasonal_adjustment: string;
  notes: string;
  source_url: string;
  license_url: string;
  updated: string;
}
export interface Snapshot {
  series: Series;
  country: string;
  retrieved_at: string;
  snapshot_id: string;
  raw_sha256: Array<string>;
  vintage: string;
  transformations: Array<string>;
  requested_start: string;
  requested_end: string;
  observations: Array<Observation>;
}
export interface Statistics {
  count: number;
  missing: number;
  mean: number | null;
  median: number | null;
  std: number | null;
  minimum: number | null;
  maximum: number | null;
  q25: number | null;
  q75: number | null;
  adf_statistic: number | null;
  adf_pvalue: number | null;
  adf_lags: number | null;
}
