"""Generate the frontend contract from Pydantic models; --check prevents drift."""

import argparse
from pathlib import Path
from typing import Any

from policysim.domain import Country, ProviderStatus, SearchResult, Snapshot
from policysim.research_contracts import (
    AnalysisRequest,
    AnalysisResult,
    CsvImportRequest,
    CsvPreview,
    ForecastRequest,
    ForecastRun,
    RunSummary,
)

TARGET = Path(__file__).resolve().parents[1] / "frontend/src/api.generated.ts"


def ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[1]
    if "anyOf" in schema:
        return " | ".join(ts(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(repr(item) for item in schema["enum"])
    kind = schema["type"]
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }[kind]


def generate() -> str:
    definitions: dict[str, Any] = {}
    for model in (
        Country,
        ProviderStatus,
        SearchResult,
        Snapshot,
        AnalysisRequest,
        AnalysisResult,
        CsvImportRequest,
        CsvPreview,
        ForecastRequest,
        ForecastRun,
        RunSummary,
    ):
        schema = model.model_json_schema(mode="serialization")
        definitions.update(schema.pop("$defs", {}))
        definitions[model.__name__] = schema
    lines = ["// Generated by scripts/generate_contracts.py. Do not edit."]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export interface {name} {{")
        for field, value in schema["properties"].items():
            expression = ts(value)
            declaration = f"  {field}: {expression};"
            if len(declaration) > 80 and expression.startswith("Array<"):
                lines.extend([f"  {field}: Array<", f"    {expression[6:-1]}", "  >;"])
            elif len(declaration) > 80 and " | " in expression:
                choices = expression.split(" | ")
                lines.append(f"  {field}:")
                lines.extend(f"    | {choice}" for choice in choices[:-1])
                lines.append(f"    | {choices[-1]};")
            else:
                lines.append(declaration)
        lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print("API contracts changed. Run uv run python scripts/generate_contracts.py.")
            return 1
    else:
        TARGET.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
